Repository RAF-SI-2024/Banka-4-Frontend, pull requests merged in 2025-04, with the labels that each got.

#239 privileges: sync with backend
  src/app/e/accounts/new/new-client.tsx
  src/app/e/accounts/new/page.tsx
  src/app/e/client/[id]/edit/page.tsx
  src/app/e/employee/[id]/edit/page.tsx
  src/app/e/employee/new/page.tsx
  src/components/client/client-form.tsx
  src/components/employee/employee-form.tsx
  src/types/privileges.ts
Labels: size/L, approved, lgtm

#242 prow: build and push FE images
  .dockerignore
  .prow/build-image.yml
  Dockerfile
  next.config.ts
Labels: approved, lgtm, size/M

#243 api/orders: map all order creation endpoints
  src/api/orders.ts
  src/api/request/orders.ts
  src/api/response/orders.ts
  src/types/orders.ts
Labels: approved, lgtm, size/M

#246 remove all fields except for code from CurrencyDto
  src/api/response/account.ts
  src/components/transfer/transfer-form.tsx
Labels: approved, lgtm, size/XS

#249 guardblock/sidebar: allow user to access if he has any of the privileges
  src/components/GuardBlock.tsx
  src/lib/sidebar-utils.ts
Labels: approved, lgtm, size/XS

#255 portfolio: map all endpoints needed for my portfolio page
  src/api/options.ts
  src/api/request/options.ts
  src/api/request/stocks.ts
  src/api/response/securities.ts
  src/api/securities.ts
  src/api/stocks.ts
  src/types/securities.ts
Labels: approved, lgtm, size/M

#257 api/taxes: map all endpoints needed for tax portal
  src/api/request/taxes.ts
  src/api/response/taxes.ts
  src/api/taxes.ts
Labels: approved, lgtm, size/M

#259 api/taxes: add `userType` filter to tax summary endpoint
  src/api/request/taxes.ts
  src/types/taxes.ts
Labels: approved, lgtm, size/XS

#260 Revert "api/taxes: add `userType` filter to tax summary endpoint"
  src/api/request/taxes.ts
  src/types/taxes.ts
Labels: approved, lgtm, size/XS

#263 api/otc: add otc endpoints
  src/api/otc.ts
  src/api/request/otc.ts
  src/api/response/otc.ts
Labels: size/L, approved, lgtm

#264 otc/overview: implement otc overview page
  src/app/u/otc/page.tsx
  src/components/otc/offer-dialog.tsx
  src/components/otc/offer-form.tsx
  src/ui/dataTables/otc/otcOverviewColumns.tsx
  src/ui/sidebar/entries.ts
Labels: size/L, approved, lgtm

#269 options: implement buy options
  src/api/options.ts
  src/api/request/options.ts
  src/api/response/account.ts
  src/app/u/(page)/[...securityType]/page.tsx
  src/components/options/buy-option-dialog.tsx
  src/components/order/OrderCreationDialog.tsx
Labels: size/L, approved, lgtm

#274 cd: automatically push front to prod every time
  .prow/build-image.yml
Labels: approved, size/XS

#275 cd: add missing k8s-banka label
  .prow/build-image.yml
Labels: approved, size/XS

#276 obscure HARBOR_PASSWORD from stdout
  .prow/build-image.yml
Labels: approved, lgtm, size/XS

#273 update app metadata
  src/app/layout.tsx
Labels: approved, lgtm, size/XS

#278 cd: run on main only
  .prow/build-image.yml
Labels: approved, lgtm, size/XS

#279 e2e: add missing valkey server
  docker-compose.yml
Labels: size/S, approved, lgtm

#281 fun with themes
  src/app/globals.css
  src/app/page.tsx
  src/components/ui/sidebar/footer-sidebar.tsx
  src/hooks/use-palette.ts
Labels: approved, lgtm, size/XXL

#282 transactions: highlight amount based on outgoing/incoming
  src/app/c/transactions/page.tsx
  src/components/client-landing-page/transactions-card.tsx
  src/ui/dataTables/transactions/transactionColumns.tsx
Labels: approved, lgtm, size/M

#283 themes: fix no theme selected when logged out
  src/app/auth/layout.tsx
  src/app/page.tsx
  src/hooks/use-palette.ts
Labels: size/S, approved, lgtm

#284 sidebar: fix icon colors
  src/components/ui/sidebar.tsx
  src/components/ui/sidebar/nav-main-sidebar.tsx
Labels: approved, lgtm, size/XS

#285 errors: change message
  src/api/errors.ts
Labels: approved, lgtm, size/XS
