Repository RAF-SI-2024/Banka-4-Frontend, pull requests merged in 2025-03, with the labels that each got.

#147 add OWNERS file
  OWNERS
Labels: size/S

#144 implement authorized person form
  package-lock.json
  src/components/company/authorized-person-form.tsx
Labels: approved, lgtm

#145 Feature/client loan overview page
  src/api/loans.ts
  src/api/response/loan.ts
  src/app/c/loans/page.tsx
  src/components/loans/LoanDialog.tsx
  src/lib/utils.ts
  src/ui/dataTables/loans/loanColumns.tsx
  src/ui/sidebar/entries.ts
Labels: size/L, approved, lgtm

#149 account/api: change getClientAccounts endpoint path
  src/api/account.ts
Labels: approved, lgtm, size/XS

#146 loan/overview: create new employee loan overview page
  src/api/loans.ts
  src/api/response/loans.ts
  src/app/e/loans/page.tsx
  src/ui/dataTables/loans/loansOverviewColums.tsx
  src/ui/sidebar/entries.ts
Labels: size/L, approved, lgtm

#154 Feature/filter improvements
  src/api/request/.gitkeep
  src/app/c/contacts/page.tsx
  src/app/c/transactions/page.tsx
  src/app/e/accounts/page.tsx
  src/app/e/employee/page.tsx
  src/app/e/loans/page.tsx
  src/components/client/client-filter-table.tsx
  src/components/dataTable/DataTable.tsx
  src/components/filters/FilterBar.tsx
  src/components/filters/FilterEnumInput.tsx
  src/components/filters/FilterInput.tsx
  src/components/filters/FilterNumberInput.tsx
  src/components/filters/FilterStringInput.tsx
  src/components/filters/FilterTimestampInput.tsx
  src/context/.gitkeep
  src/hooks/.gitkeep
  src/types/.gitkeep
Labels: approved, lgtm, size/XL

#160 add number filter
  src/components/filters/FilterNumberInput.tsx
Labels: approved, lgtm, size/M

#155 add first iteration API connection update for contacts page and desig…
  src/api/contact.ts
  src/api/request/contact.ts
  src/api/response/contact.ts
  src/app/c/contacts/page.tsx
  src/components/contacts/contact-form-dialog.tsx
  src/components/contacts/contact-form.tsx
  src/ui/dataTables/contacts/contactsColumns.tsx
Labels: size/L, approved, lgtm

#156 genders: refactor our genders to be of type "MALE" | "FEMALE"
  src/app/e/accounts/new/new-client.tsx
  src/app/e/employee/new/page.tsx
  src/components/client/client-form.tsx
  src/components/company/authorized-person-form.tsx
  src/components/employee/employee-form.tsx
  src/types/gender.ts
Labels: approved, lgtm, size/M

#161 Feature/finalize new payment page
  src/api/account.ts
  src/api/client.ts
  src/api/request/client.ts
  src/api/request/transaction.ts
  src/api/response/client.ts
  src/app/c/transactions/new-payment/page.tsx
  src/components/client/new-transaction-form.tsx
Labels: size/L, approved, lgtm

#165 Feature/extend client landing page
  src/api/cards.ts
  src/api/request/card.ts
  src/api/response/account.ts
  src/api/response/cards.ts
  src/app/c/page.tsx
  src/app/e/cards/page.tsx
  src/components/cards/AuthorizedPersonDialogForm.tsx
  src/components/cards/card-info-dialog.tsx
  src/components/cards/card-info-form.tsx
  src/components/client-landing-page/cards-table-card.tsx
  src/components/client-landing-page/transactions-card.tsx
  src/components/company/authorized-person-form.tsx
  src/types/account.ts
  src/types/card.ts
  src/ui/cards/cardColumns.tsx
Labels: approved, lgtm, size/XL

#163 Feature/loan requests page
  package-lock.json
  src/api/loans.ts
  src/api/response/loan.ts
  src/api/response/loans.ts
  src/app/c/loans/page.tsx
  src/app/e/loans/page.tsx
  src/app/e/loans/requests/page.tsx
  src/types/loan.ts
  src/ui/dataTables/loans/loansOverviewColums.tsx
  src/ui/sidebar/entries.ts
Labels: size/L, approved, lgtm

#157 add intial design for loan request form and page
  src/api/loan.ts
  src/api/request/loan.ts
  src/app/c/loans/request/page.tsx
  src/app/e/loans/requests/page.tsx
  src/components/loans/loan-form-card.tsx
  src/components/loans/loan-form.tsx
  src/lib/form-utils.ts
  src/types/loan.ts
  src/types/utils.ts
  src/ui/sidebar/entries.ts
Labels: approved, lgtm, size/XL

#166 Feature/exchange page
  src/api/exchange.ts
  src/api/response/exchange.ts
  src/app/c/exchange/page.tsx
  src/types/card.ts
  src/ui/dataTables/exchange/exchange-column.tsx
  src/ui/sidebar/entries.ts
Labels: size/L, approved, lgtm

#162 implement 2FA on transfer page
  src/api/request/transfer.ts
  src/app/c/transactions/transfer/page.tsx
  src/components/transfer/transfer-form.tsx
Labels: approved, lgtm, size/M

#181 auth/api: change method of forgot password request
  src/api/auth.ts
Labels: approved, lgtm, size/XS

#175 fix creating new account
  src/api/request/account.ts
  src/app/e/accounts/new/page.tsx
Labels: approved, lgtm, size/XS

#183 fix bug on client landing page for new payment button
  src/components/account/account-carousel.tsx
Labels: approved, lgtm, size/XS

#188 Finished more information dialog
  src/api/response/company.ts
  src/app/c/page.tsx
  src/components/account/account-carousel.tsx
  src/components/account/view-account-form.tsx
  src/types/transaction.ts
Labels: approved, lgtm, size/M

#186 currency: refactor currencies to be same pattern as loan
  src/components/account/account-form.tsx
  src/components/loans/loan-form.tsx
  src/types/currency.ts
Labels: size/S, approved, lgtm

#189 add loginblock component for redirecting user
  src/app/auth/login/page.tsx
  src/app/page.tsx
  src/components/LoginBlock.tsx
Labels: size/L, approved, lgtm

#193 Fix check alignment
  src/components/ui/select.tsx
Labels: approved, lgtm, size/XS

#212 Finished create card request
  src/api/request/card.ts
  src/app/c/page.tsx
Labels: approved, lgtm, size/XS

#214 fix: reset otp in 2fa dialog
  src/components/Dialog2FA.tsx
Labels: approved, lgtm, size/XS

#217 card-overview: apply accountNumber filter immediately, change the red…
  src/app/e/cards/page.tsx
  src/ui/dataTables/accounts/accounts-columns.tsx
Labels: size/S, approved, lgtm

#219 Bugfix/disable date of birth
  src/components/client/client-form.tsx
  src/components/employee/employee-form.tsx
Labels: approved, lgtm, size/XS

#232 card/info: fix bad owner being displayed
  src/api/response/cards.ts
  src/components/client-landing-page/cards-table-card.tsx
Labels: approved, lgtm

#235 loan/form: remove min amount validation on Input element
  src/components/loans/loan-form.tsx
Labels: approved, lgtm, size/XS
